POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "g59@email.com",
    "password": "ugliestg59"
}

###
GET http://localhost:8000/users

###

GET http://localhost:8000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiZzU5QGVtYWlsLmNvbSIsImlhdCI6MTczOTY0NTcxNywiZXhwIjoxNzM5NjQ5MzE3fQ.oS71H-fDW_LHuI4ikH4ePfO3FEz1FbHlpVrr_TYws2w

###
GET http://localhost:8000/events

###
GET http://localhost:8000/events/search?search=tech
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiZzU5QGVtYWlsLmNvbSIsImlhdCI6MTczOTY0NTcxNywiZXhwIjoxNzM5NjQ5MzE3fQ.oS71H-fDW_LHuI4ikH4ePfO3FEz1FbHlpVrr_TYws2w


###
POST http://localhost:8000/events
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiZzU5QGVtYWlsLmNvbSIsImlhdCI6MTczOTQxNDk4MSwiZXhwIjoxNzM5NDE4NTgxfQ.LPniqpi0kPewfCsFlSD83cN_F1onnKMysie8fm2xF2Y

{
    "title": "Hack-Nation",
    "description":"Convention showcasing tech for white hat hackers. Competitions, prizes, and more!",
    "startDate":"02/22/2025",
    "endDate":"02/23/2025",
    "location":"Houston",
    "genre":"Tech"
}

###
POST http://localhost:8000/events/1/rsvp
Content-Type: application/json

{
    "user_id":7,
    "status": "going"
}

###
DELETE http://localhost:8000/events/1/rsvp
Content-Type: application/json

{
    "user_id": 7
}

###
GET http://localhost:8000/events/1/rsvps

###
GET http://localhost:8000/events

